{% set name = "tigernet" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tigernet-{{ version }}.tar.gz
  sha256: 0137ecd531cb394e0d61b61e8fd7d0bd02ac0923a8f9f6cf11962f3b2eadf3ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - black
    - codecov
    - gdal >=3.3.0
    - geopandas >=0.9.0
    - libpysal
    - numpy
    - pandas
    - pre-commit
    - pygeos >=0.8
    - pytest
    - pytest-cov
    - shapely >=1.7.1
    - spaghetti

test:
  imports:
    - tigernet
    - tigernet.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jGaboardi/tigernet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'tigernet: Network Topology via TIGER/Line Edges'
  description: |
    TigerNet is an open-source Python library that addresses concerns in topology and builds accurate spatial network representations from [TIGER/Line data](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html), specifically [TIGER/Line edges](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2017/TGRSHP2017_TechDoc_Ch4.pdf).
  doc_url: https://jgaboardi.github.io/tigernet/
  dev_url: https://github.com/jGaboardi/tigernet

extra:
  recipe-maintainers:
    - jGaboardi
