{% set name = "tigernet" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tigernet-{{ version }}.tar.gz
  sha256: 93da7c360e21c2e4f1ea06c60f49d5269aaa7dccfeb3219191dd64d41d744527

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - black
    - codecov
    - gdal >=3.3.0
    - geopandas >=0.9.0
    - libpysal
    - numpy
    - pandas
    - pre-commit
    - pyamg
    - pygeos >=0.8
    - pytest
    - pytest-cov
    - pytest-xdist
    - shapely >=1.7.1
    - spaghetti
    - versioneer

test:
  imports:
    - tigernet
    - tigernet.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jGaboardi/tigernet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'tigernet: Network Topology via TIGER/Line Edges'
  description: |
    TigerNet is an open-source Python library that addresses concerns in topology and builds accurate spatial network representations from [TIGER/Line data](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html), specifically [TIGER/Line edges](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2017/TGRSHP2017_TechDoc_Ch4.pdf).
  doc_url: https://jgaboardi.github.io/tigernet/
  dev_url: https://github.com/jGaboardi/tigernet

extra:
  recipe-maintainers:
    - jGaboardi
